language: ruby
before_install:
  - sudo apt-get install zsh
script:
  - zsh -c "source theme.zsh" || { echo "failed to source" ; exit 1 ; }
notifications:
  email:
    on_success: change
    on_failure: always

